### ISSUE TITLE
Links for reference

### ISSUE THREAD

**Issue by Chandana13Rao** [Karthik-d-k/picars#18]
**Advanced lane detection blog:**
https://towardsdatascience.com/advanced-lane-detection-for-autonomous-vehicles-using-computer-vision-techniques-f229e4245e41
**Github link:**
https://github.com/uppala75/CarND-Advanced-Lane-Lines/tree/master
**Theta code :** 
https://www.hackster.io/Aasai/lane-following-robot-using-opencv-da3d45

**Comment by Karthik-d-k** [comment]
Thanks Chandana :)
